import { regular_font } from "@/lib/fornts"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className={regular_font.className}>{children}</div>
  )
}
