backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "public/imgs/posts" # Media files will be stored in the repo under static/images/uploads
public_folder: "/imgs/posts" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descipción", name: "description", widget: "string"}
      - {label: "Fecha", name: "pubDate", widget: "datetime"}
      - {label: "Imagen principal", name: "heroImage", widget: "image"}
      - {label: "Categoría", name: "category", widget: list, default: ['tech', 'psicologia']}
      - {label: "Contenido", name: "body", widget: "markdown"}